### 모든 UserList 조회 가능
GET http://localhost:8200/api/user/admin/userList?page=1&size=3
Accept: application/json

###

GET http://localhost:8200/api/user/admin/userList/sort/1?page=1&size=2
Accept: application/json

###

POST http://localhost:8200/api/user/admin/promotion
Content-Type: application/json

{
  "id": "zxcv"
}

###

#POST http://localhost:8200/api/user/admin/demotion
#Content-Type: application/json
#
#{
#  "id": "asdf"
#}

###

POST http://localhost:8200/api/user/admin/permit
Content-Type: application/json

[
  {
    "id": "asdf"
  },
  {
    "id": "zxcv"
  }
]

###

POST http://localhost:8200/api/user/admin/reject/delete
Content-Type: application/json

[
  {
    "id": "asdf"
  },
  {
    "id": "zxcv"
  }
]

###

DELETE http://localhost:8200/api/user/admin/delete
Content-Type: application/json

[
  {
    "id": "zxcv"
  },
  {
    "id": "asdf"
  }
]