// 모든 UserList 조회 가능
GET http://localhost:8200/api/user/admin/userList
Accept: application/json

###

GET http://localhost:8200/api/user/admin/userList/sort/status/1
Accept: application/json

###

GET http://localhost:8200/api/user/admin/userList/sort/role/1
Accept: application/json

###

POST http://localhost:8200/api/user/admin/promotion
Content-Type: application/json

{
  "id": "zxcv"
}

###

POST http://localhost:8200/api/user/admin/permit
Content-Type: application/json

[
  {
    "id": "zxcv"
  }
]

###

POST http://localhost:8200/api/user/admin/reject/delete
Content-Type: application/json

[
  {
    "id": "asdf"
  },
  {
    "id": "zxcv"
  }
]

###

DELETE http://localhost:8200/api/user/admin/delete
Content-Type: application/json

[
  {
    "id": "zxcv"
  },
  {
    "id": "asdf"
  }
]