POST http://localhost:8200/api/admin/status/1
Content-Type: application/json

{

}

###

POST http://localhost:8200/api/admin/status/2
Content-Type: application/json

{

}

###

POST http://localhost:8200/api/admin/status/3
Content-Type: application/json

{

}

###