GET http://localhost:8200/api/user
Accept: application/json

###

GET http://localhost:8200/api/user/myPage
X-USER-ID:jjunho50
Accept: application/json

###

POST http://localhost:8200/api/user/login
Content-Type: application/json

{
  "id": "jjunho50",
  "password": "1234"
}

###

POST http://localhost:8200/api/user
Content-Type: application/json

{
  "id": "jjunho50",
  "name": "정준호",
  "password": "1234",
  "email": "jjunho50@gmail.com",
  "birth": "19991102"
}

###

PUT http://localhost:8200/api/user
X-USER-ID:jjunho50
Content-Type: application/json

{
  "id": "jjunho50",
  "name": "정준호",
  "password": "1234",
  "email": "updated@gmail.com",
  "birth": "19991102"
}

###

DELETE http://localhost:8200/api/user
X-USER-ID:jjunho50