
// 모든 UserList 조회 가능
GET http://localhost:8200/api/user?page=0&size=3
X-USER-ID:admin
Accept: application/json

###

GET http://localhost:8200/api/user/myPage
X-USER-ID:test2
Accept: application/json

###

POST http://localhost:8200/api/user/login
Content-Type: application/json

{
  "id": "admin",
  "password": "1234"
}

###

POST http://localhost:8200/api/user/register
Content-Type: application/json

{
  "id": "asdf",
  "name": "asdf",
  "password": "asdf",
  "email": "asdf@gmail.com"
}

###

PUT http://localhost:8200/api/user/update
X-USER-ID:admin
Content-Type: application/json

{
  "id": "admin",
  "name": "admin",
  "password": "1234",
  "email": "admin@gmail.com"
}

###

DELETE http://localhost:8200/api/user/delete
X-USER-ID:test2

###

